/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/renderer/**/*.{js,ts,jsx,tsx,html}',
  ],
  theme: {
    extend: {
      colors: {
        // FlowState warm, earthy color palette (legacy tokens)
        flowstate: {
          primary: '#8B6B59',
          secondary: '#665F5D',
          background: '#F6EEE3',
          surface: '#E8DFD3',
          card: '#FFFFFF',
          text: '#1E1E1E',
          'text-muted': '#5A5A5A',
          accent: '#331C16',
          success: '#4A7C59',
          warning: '#D4A574',
          error: '#C45B4A',
          border: '#D4C9BD',
          selection: '#C9B8A8',
          highlight: '#DED4C7',
          overlay: 'rgba(30, 30, 30, 0.75)',
        },
        // Mockup UI tokens (CSS variables)
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        popover: 'var(--popover)',
        'popover-foreground': 'var(--popover-foreground)',
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        destructive: 'var(--destructive)',
        'destructive-foreground': 'var(--destructive-foreground)',
        border: 'var(--border)',
        input: 'var(--input)',
        'input-background': 'var(--input-background)',
        'switch-background': 'var(--switch-background)',
        ring: 'var(--ring)',
        sidebar: 'var(--sidebar)',
        'sidebar-foreground': 'var(--sidebar-foreground)',
        'sidebar-primary': 'var(--sidebar-primary)',
        'sidebar-primary-foreground': 'var(--sidebar-primary-foreground)',
        'sidebar-accent': 'var(--sidebar-accent)',
        'sidebar-accent-foreground': 'var(--sidebar-accent-foreground)',
        'sidebar-border': 'var(--sidebar-border)',
        'sidebar-ring': 'var(--sidebar-ring)',
        // Semantic colors
        semantic: {
          approval: '#4A7C59',
          pending: '#D4A574',
          denied: '#C45B4A',
          info: '#8B6B59',
          connected: '#4A7C59',
          disconnected: '#C45B4A',
        },
      },
      fontFamily: {
        sans: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'sans-serif',
        ],
      },
      borderRadius: {
        'flowstate': '12px',
      },
      boxShadow: {
        'flowstate': '0 2px 8px rgba(139, 107, 89, 0.12)',
        'flowstate-lg': '0 4px 16px rgba(139, 107, 89, 0.16)',
      },
    },
  },
  plugins: [],
};
